# Generated by Django 3.1.3 on 2021-01-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='userFollower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFollower', to=settings.AUTH_USER_MODEL),
        ),
    ]
