# Generated by Django 3.1.3 on 2021-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
