# Generated by Django 3.1.3 on 2020-12-09 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_listingcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 9, 1, 46, 38, 274550, tzinfo=utc)),
        ),
    ]
