# Generated by Django 3.1.3 on 2020-12-09 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201209_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 9, 7, 1, 24, 806767, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comments',
            name='commentSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 9, 7, 1, 24, 807170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bidPrice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 9, 7, 1, 24, 806262, tzinfo=utc)),
        ),
    ]
