# Generated by Django 3.1.3 on 2020-12-10 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201210_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlistUser',
            new_name='watchlistUserID',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlistActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bidSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 2, 37, 59, 338893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 2, 37, 59, 339286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 10, 2, 37, 59, 338459, tzinfo=utc)),
        ),
    ]
