# Generated by Django 3.1.3 on 2020-12-11 05:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201211_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listingWinner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bidSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 5, 53, 8, 427419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 5, 53, 8, 427802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 5, 53, 8, 426976, tzinfo=utc)),
        ),
    ]
