# Generated by Django 3.1.3 on 2020-12-11 08:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201211_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 8, 18, 30, 365691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 8, 18, 30, 366138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 8, 18, 30, 364876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listinguser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingWinner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
