# Generated by Django 3.1.3 on 2020-12-13 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20201211_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 53, 4, 94472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 53, 4, 94859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 3, 53, 4, 94046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingImage',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
