# Generated by Django 3.1.3 on 2020-12-13 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20201213_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 4, 12, 19, 151356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentSubmitted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 4, 12, 19, 151740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 13, 4, 12, 19, 150932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listingDesc',
            field=models.CharField(max_length=2000),
        ),
    ]
